Repository dc-tec/nixvim, pull requests merged in 2024-10, with the labels that each got.

#42 chore(deps): update renovatebot/github-action action to v40.3.1
  .github/workflows/renovate.yaml
Labels: renovate

#43 deps: update flake.lock
  flake.lock
Labels: dependencies, automated

#45 deps: update flake.lock
  flake.lock
Labels: dependencies, automated

#44 chore(deps): update renovatebot/github-action action to v40.3.3
  .github/workflows/renovate.yaml
Labels: renovate

#46 chore(deps): update renovatebot/github-action action to v40.3.4
  .github/workflows/renovate.yaml
Labels: renovate

#47 deps: update flake.lock
  flake.lock
Labels: dependencies, automated

#49 renamed changed lsp names and use web-devicons as a full plugin
  config/default.nix
  config/plugins/lsp/lsp.nix
  config/plugins/utils/extra_plugins.nix
  config/plugins/utils/web-devicons.nix
Labels: bug

#50 Change nix formater from alejandra to nixfmt-rfc-style
  config/plugins/lsp/conform.nix
  flake.nix
Labels: enhancement
