Repository dc-tec/nixvim, pull requests merged in 2025-01, with the labels that each got.

#69 config/plugins/lsp: Stop after first formatter
  config/plugins/lsp/conform.nix
Labels: enhancement

#68 deps: update flake.lock
  flake.lock
Labels: dependencies, automated

#70 chore(deps): update renovatebot/github-action action to v41.0.7
  .github/workflows/renovate.yaml
Labels: renovate
